<?php

use Krystal\Form\Element;

?>

<style>

.album {
    position: relative;
}

.album img {
    
}

.album a {
    position: absolute;
    background: #da6565;
    padding: 7px;
    color: #fff;
    font-size: 10px;
}

</style>

<div class="mb-2">
    <form method="POST" action="<?= $this->url('Album:Album@uploadAction'); ?>">
        <div class="form-group">
            <?= Element::file('file'); ?>
        </div>

        <?= Element::submit(
            $this->translate('Upload new photo'),
            ['class' => 'btn btn-success']
        ); ?>
    </form>
</div>

<?php if (!empty($photos)): ?>
<section class="album">

    <?php foreach ($photos as $photo): ?>
    <a href="<?= $this->url('Album:Album@deleteAction', [$photo->getId()]); ?>"><i class="far fa-trash-alt"></i></a>
    <img src="<?= $photo->getImageBag()->getUrl('original'); ?>" class="img-fluid" />
    <?php endforeach; ?>

</section>
<?php endif; ?>